/// <reference types="cypress" />

describe('Create Sale', () => {
  for (let i = 0; i < 2; i++) {
    before(() => {
      cy.exec('mongosh mongodb://localhost:27017 --eval "db.getSiblingDB(\'system-database\').dropDatabase()"')
    })

    beforeEach(() => {
      cy.visit('http://localhost:3000/')
    })

    it('Create sale ' + (i == 0 ? ' - desktop' : ' - mobile'), () => {
      cy.wait(1000)
      cy.wait(1000)
      if (i == 0) {
        cy.viewport(1920, 1080)
        cy.get('#link-login').click()

      } else {
        cy.viewport(412, 915)
        cy.exec('mongosh mongodb://localhost:27017 --eval "db.getSiblingDB(\'system-database\').dropDatabase()"')
        cy.get('#navbar-toggler').click()
        cy.get('#link-login').click()
        cy.get('#navbar-toggler').click()
      }
      cy.get('#button-commom-register').click()
      cy.get('#input-name').type('Company Of Tests')
      cy.get('#input-email').type('sale-tests@gmail.com')
      cy.get('#input-username').type('sale-tests')
      cy.get('#input-password-singin').type('1234*Abcd')
      cy.get('#input-passwordConfirmation').type('1234*Abcd')
      cy.get('#button-commom-register-singin').click()
      cy.wait(1000)
      cy.get('#link-categories').click()
      cy.wait(1000)
      cy.get('#button-commom-add-category').click()
      cy.get('#input-type').click()
      cy.get('#option-0').click()
      cy.get('#input-name').type('Category')
      cy.get('#input-description').type('Description of Category')
      cy.get('#button-success-save-edit-category').click()
      cy.get('#confirm-text-save').should('have.text', 'Deseja salvar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Salvo com sucesso!')
      cy.get('#confirm-text-ok').click()
      cy.get('#icon-bar-menu').click()
      cy.get('#link-sales').click()
      cy.wait(1000)
      cy.get('#button-commom-add-sale').click()
      cy.get('#add-new-customer').click()
      cy.get('#input-name').type('Customer Of Tests')
      cy.get('#input-cpf').type('000.000.000-00')
      cy.get('#input-birthday').type('01/01/2023')
      cy.get('#input-gender').click()
      cy.get('#option-0').click()
      cy.get('#input-nickname').type('customernickname')
      cy.get('#input-phoneNumber').type('11999999999')
      cy.get('#input-email').type('customer-tests@gmail.com')
      cy.get('#input-additionalInformation').type('Customer Additional Information')
      cy.get('#input-zipCode').type('32180640')
      cy.wait(1000)
      cy.get('#input-houseNumber').type('1500')
      cy.get('#input-complement').type('House A')
      cy.get('#button-success-save-edit-customer').click()
      cy.get('#confirm-text-save').should('have.text', 'Deseja salvar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Salvo com sucesso!')
      cy.get('#confirm-text-ok').click()
      cy.get('#input-customer').click()
      cy.get('#option-0').click()
      cy.get('#input-description').click()
      cy.get('#add-new-product-0').click()
      cy.get('#input-name').type('Product of sale 1')
      cy.get('#input-category').click()
      cy.get('#option-0').click()
      cy.get('#input-price').type('1099')
      cy.get('#input-quantityInStock').type('10')
      cy.get('#button-success-save-edit-product').click()
      cy.get('#confirm-text-save').should('have.text', 'Deseja salvar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Salvo com sucesso!')
      cy.get('#confirm-text-ok').click()
      cy.get('#input-productId-0').click()
      cy.get('#option-0').click()
      cy.get('#add-product-0').click()
      cy.get('#add-new-product-1').click()
      cy.get('#input-name').type('Service of sale 2')
      cy.get('#input-category').click()
      cy.get('#option-0').click()
      cy.get('#input-price').type('5099')
      cy.get('#input-quantityInStock').type('100')
      cy.get('#button-success-save-edit-product').click()
      cy.get('#confirm-text-save').should('have.text', 'Deseja salvar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Salvo com sucesso!')
      cy.get('#confirm-text-ok').click()
      cy.get('#input-productId-1').click()
      cy.get('#option-1').click()
      cy.get('#input-formOfPayment').click()
      cy.get('#option-0').click()
      cy.get('#option-1').click().trigger('keydown', { keyCode: 27, which: 27 })
      cy.get('#input-discount').type('1000')
      cy.get('#input-informationAboutTheSale').type('Information About The Sale with discount')
      cy.get('#button-success-save-edit-sale').click()
      cy.get('#confirm-text-save').should('have.text', 'Deseja salvar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Salvo com sucesso!')
      cy.get('#confirm-text-ok').click()
    })

    it('Read sale ' + (i == 0 ? ' - desktop' : ' - mobile'), () => {
      cy.wait(1000)
      if (i == 0) {
        cy.viewport(1920, 1080)
        cy.get('#link-login').click()
      } else {
        cy.viewport(412, 915)
        cy.get('#navbar-toggler').click()
        cy.get('#link-login').click()
        cy.get('#navbar-toggler').click()
      }
      cy.get('#input-username').type('sale-tests')
      cy.get('#input-password').type('1234*Abcd')
      cy.wait(1000)
      cy.get('#button-login').click()
      cy.get('#link-sales').click()
      cy.wait(1000)
      cy.get('#details-0').click()
      cy.wait(1000)
      cy.get('#label-saleNumber').should('have.text', 'NÚMERO: ')
      cy.get('#value-saleNumber').should('have.text', '1')
    })

    it('Update sale ' + (i == 0 ? ' - desktop' : ' - mobile'), () => {
      cy.wait(1000)
      if (i == 0) {
        cy.viewport(1920, 1080)
        cy.get('#link-login').click()
      } else {
        cy.viewport(412, 915)
        cy.get('#navbar-toggler').click()
        cy.get('#link-login').click()
        cy.get('#navbar-toggler').click()
      }
      cy.get('#input-username').type('sale-tests')
      cy.get('#input-password').type('1234*Abcd')
      cy.wait(1000)
      cy.get('#button-login').click()
      cy.get('#link-sales').click()
      cy.wait(1000)
      cy.get('#edit-0').click()
      cy.wait(1000)
      cy.get('#input-productId-1').click()
      cy.get('#option-0').click()
      cy.get('#button-success-save-edit-sale').click()
      cy.get('#confirm-text-edit').should('have.text', 'Deseja editar as informações?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-save').should('have.text', 'Editado com sucesso!')
      cy.get('#confirm-text-ok').click()
      cy.wait(1000)
      cy.get('#details-0').click()
      cy.get('#close-modal-details').click()
    })

    it('Delete sale ' + (i == 0 ? ' - desktop' : ' - mobile'), () => {
      cy.wait(1000)
      if (i == 0) {
        cy.viewport(1920, 1080)
        cy.get('#link-login').click()
      } else {
        cy.viewport(412, 915)
        cy.get('#navbar-toggler').click()
        cy.get('#link-login').click()
        cy.get('#navbar-toggler').click()
      }
      cy.get('#input-username').type('sale-tests')
      cy.get('#input-password').type('1234*Abcd')
      cy.wait(1000)
      cy.get('#button-login').click()
      cy.get('#link-sales').click()
      cy.wait(1000)
      cy.get('#delete-0').click()
      cy.wait(1000)
      cy.get('#confirm-text-delete').should('have.text', 'Você tem certeza que quer apagar esta informação?')
      cy.get('#confirm-text-yes').click()
      cy.get('#confirm-text-delete').should('have.text', 'Informação deletada com sucesso!')
      cy.get('#confirm-text-ok').click()

    })
  }
})