
 

name: Node.js deploy
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      
      - name: Run tests
        uses: actions/checkout@v3
      - run: echo "RUN TEST============"
    
  run-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
            